export const NICHE_OPTIONS = [
  { value: '', label: '' },
  { value: 'ecommerce', label: 'E-Commerce' },
  { value: 'saas', label: 'SaaS / Tech' },
  { value: 'health', label: 'Health & Wellness' },
  { value: 'fitness', label: 'Fitness / Coaching' },
  { value: 'realestate', label: 'Real Estate' },
  { value: 'finance', label: 'Finance / Insurance' },
  { value: 'education', label: 'Education / Courses' },
  { value: 'food', label: 'Food & Beverage' },
  { value: 'beauty', label: 'Beauty / Skincare' },
  { value: 'local', label: 'Local Service Business' },
  { value: 'agency', label: 'Agency / B2B' },
  { value: 'other', label: 'Other' },
]
